name = "DaCaganFam"
author = "AviC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29408c60237f0c333acc62c4fe40632a11bb63de1cb536a3ddc4262754178b33"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
