name = "DaCaganFam"
author = "AviC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7202f5c91e0a490e96931aacd3ae0f02ee22595fa84358762ac5bacbbe062978"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
