name = "DaCaganFam"
author = "AviC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbeca1c415564d4d85f8c65f2870bb2766bbbf2649397c1076bda5fbaae04937"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
